//prompt a user to enter a number 
//save it in a variable
//display rock is equals to zero ,paper is equals to one ,scissors is equals to two
//make the computer output random numbers from zero to three
//compare the number inputted by the user and the one generated by the computer
//check if the number inputted by the user is 1 and the number generated by the computer is 0
//display "The computer is rock."  "You are paper."  "You won", if not
//check if the number inputted by the user is two and the number generated by the computer is one
//display "The computer is paper."  "You are scissors."  "You won"
//check if the number inputted by the user is 0 and the number generated by the computer is 2
//dislay "The computer is scissors."  "You are rock."  "You lose"
//check if the number inputted by the user is 0 and the number generated by the computer is 1
//display "The computer is paper."  "You are rock."  "You lose"
//check if the number inputted by the user is 1 and the number generated by the computer is 2
//display "The computer is scissors."  "You are paper."  "You lose"
//check if the number inputted by the user is equal to the number generated by the computer
//display "It is a draw"


import java.util.Scanner;

public class Game{

public static void main(String[] args){

Scanner scanner = new Scanner(System.in);

int choiceComputer = (int) (Math.random() * 3);

System.out.println("Choose from the following");
System.out.println("rock (0)");
System.out.println("paper (1)");
System.out.println("scissors (2)");
System.out.print("Enter your choice: ");
int choice = scanner.nextInt();


if(choice == 1 && choiceComputer == 0){

System.out.print("The computer is rock.");
System.out.print("You are paper.");
System.out.println("You won");
}

else if(choice == 2 && choiceComputer == 1){

System.out.print("The computer is paper.");
System.out.print("You are scissors.");
System.out.println("You won");
}

else if(choice == 0 && choiceComputer == 2){
System.out.print("The computer is scissors.");
System.out.print("You are rock.");
System.out.println("You lose");


}

else if(choice == 0 && choiceComputer == 1){
System.out.print("The computer is paper.");
System.out.print("You are rock.");
System.out.println("You lose");


}

else if(choice == 1 && choiceComputer == 2){
System.out.print("The computer is scissors.");
System.out.print("You are paper.");
System.out.println("You lose");


}

else if(choice == 2 && choiceComputer == 0){
System.out.print("The computer is rock.");
System.out.print("You are scissors.");
System.out.println("You lose");


}

else if(choice == choiceComputer){

System.out.print("It is a draw");

}






}
}